#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
#debug: false
#server 地址
server_url: "0.0.0.0:80"

#相对应若依平台的VITE_APP_BASE_API
base_api: "/prod-api"

#接口白名单（免登陆直接访问）
white_list_api:
  - "/"
  - "/prod-api/login"
  - "/prod-api/logout"
  - "/prod-api/captchaImage"